# Generated by Django 4.2.7 on 2026-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID клиента')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон клиента')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента')),
                ('client_company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('client_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип клиента')),
                ('client_bin_iin', models.CharField(blank=True, max_length=20, null=True, verbose_name='БИН/ИИН')),
                ('client_address', models.TextField(blank=True, null=True, verbose_name='Адрес клиента')),
                ('client_bik', models.TextField(blank=True, null=True, verbose_name='БИК')),
                ('client_iik', models.TextField(blank=True, null=True, verbose_name='ИИК')),
                ('client_bankname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
    ]
