# Generated by Django 4.2.7 on 2026-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID производителя')),
                ('manufacturer_name', models.CharField(max_length=255, unique=True, verbose_name='Название производителя')),
                ('manufacturer_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производителя')),
                ('manufacturer_website', models.URLField(blank=True, null=True, verbose_name='Сайт производителя')),
                ('manufacturer_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturer',
            },
        ),
    ]
