# Generated by Django 4.2.7 on 2026-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTypes',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID типа')),
                ('type_name', models.CharField(max_length=255, unique=True, verbose_name='Название типа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'equipment_types',
            },
        ),
    ]
