# Generated by Django 4.2.7 on 2026-01-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_equipmenttypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID детали')),
                ('detail_parameter_name', models.CharField(max_length=255, verbose_name='Название параметра')),
                ('detail_parameter_value', models.TextField(blank=True, null=True, verbose_name='Значение параметра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Деталь оборудования',
                'verbose_name_plural': 'Детали оборудования',
                'db_table': 'equipment_details',
            },
        ),
    ]
