# Generated by Django 4.2.7 on 2026-01-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_equipmentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSpecification',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID спецификации')),
                ('spec_parameter_name', models.CharField(max_length=255, verbose_name='Название параметра')),
                ('spec_parameter_value', models.TextField(blank=True, null=True, verbose_name='Значение параметра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Спецификация оборудования',
                'verbose_name_plural': 'Спецификации оборудования',
                'db_table': 'equipment_specification',
            },
        ),
        migrations.CreateModel(
            name='EquipmentTechProcess',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID процесса')),
                ('tech_name', models.CharField(max_length=255, verbose_name='Название процесса')),
                ('tech_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('tech_desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Технологический процесс оборудования',
                'verbose_name_plural': 'Технологические процессы оборудования',
                'db_table': 'equipment_tech_proccess',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID оборудования')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('equipment_articule', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('equipment_uom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
                ('equipment_short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('equipment_warranty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантия')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано на сайте')),
                ('equipment_imagelinks', models.TextField(blank=True, null=True, verbose_name='Ссылки на изображения')),
                ('equipment_videolinks', models.TextField(blank=True, null=True, verbose_name='Ссылки на видео')),
                ('equipment_manufacture_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена производства')),
                ('equipment_madein_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства')),
                ('equipment_price_currency_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип валюты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='proposals.category', verbose_name='Категория')),
                ('detail', models.ForeignKey(blank=True, db_column='detail_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='proposals.equipmentdetails', verbose_name='Детали оборудования')),
                ('equipment_tech_process', models.ForeignKey(blank=True, db_column='equipment_tech_process_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='proposals.equipmenttechprocess', verbose_name='Технологический процесс')),
                ('equipment_type', models.ForeignKey(blank=True, db_column='equipment_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='proposals.equipmenttypes', verbose_name='Тип оборудования')),
                ('manufacturer', models.ForeignKey(blank=True, db_column='manufacturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='proposals.manufacturer', verbose_name='Производитель')),
                ('spec', models.ForeignKey(blank=True, db_column='spec_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='proposals.equipmentspecification', verbose_name='Спецификация оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
            },
        ),
    ]
