# Generated by Django 4.2.7 on 2026-01-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_equipmentspecification_equipmenttechprocess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_tech_process',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='spec',
        ),
        migrations.AddField(
            model_name='equipment',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='proposals.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_types',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='proposals.equipmenttypes', verbose_name='Типы оборудования'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='proposals.manufacturer', verbose_name='Производители'),
        ),
        migrations.AddField(
            model_name='equipmentdetails',
            name='equipment',
            field=models.ForeignKey(blank=True, db_column='equipment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='proposals.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='equipmentspecification',
            name='equipment',
            field=models.ForeignKey(blank=True, db_column='equipment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='proposals.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='equipmenttechprocess',
            name='equipment',
            field=models.ForeignKey(blank=True, db_column='equipment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_processes', to='proposals.equipment', verbose_name='Оборудование'),
        ),
    ]
