# Generated by Django 4.2.7 on 2026-01-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_remove_equipment_category_remove_equipment_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePrice',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID цены')),
                ('source_type', models.CharField(choices=[('russia', 'Russia'), ('china', 'China'), ('own_production', 'Own Production'), ('other', 'Other')], max_length=20, verbose_name='Источник')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена закупки')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='proposals.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Цена закупки',
                'verbose_name_plural': 'Цены закупки',
                'db_table': 'purchase_price',
            },
        ),
    ]
