# Generated by Django 4.2.7 on 2026-01-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_purchaseprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLine',
            fields=[
                ('equipment_line_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID линии оборудования')),
                ('equipment_line_name', models.CharField(max_length=255, verbose_name='Название линии оборудования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Линия оборудования',
                'verbose_name_plural': 'Линии оборудования',
                'db_table': 'equipment_line',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('logistics_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID логистики')),
                ('route_type', models.CharField(choices=[('china_kz', 'China to KZ'), ('russia_kz', 'Russia to KZ'), ('kz_warehouse', 'KZ Warehouse'), ('other', 'Other')], max_length=20, verbose_name='Маршрут')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость доставки')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('estimated_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='proposals.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Логистика',
                'verbose_name_plural': 'Логистика',
                'db_table': 'logistics',
            },
        ),
        migrations.CreateModel(
            name='EquipmentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='proposals.equipment', verbose_name='Оборудование')),
                ('equipment_line', models.ForeignKey(db_column='equipment_line_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='proposals.equipmentline', verbose_name='Линия оборудования')),
            ],
            options={
                'verbose_name': 'Элемент линии оборудования',
                'verbose_name_plural': 'Элементы линии оборудования',
                'db_table': 'equipment_line_item',
                'ordering': ['order'],
                'unique_together': {('equipment_line', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='equipmentline',
            name='equipment',
            field=models.ManyToManyField(related_name='equipment_lines', through='proposals.EquipmentLineItem', to='proposals.equipment', verbose_name='Оборудование'),
        ),
        migrations.CreateModel(
            name='EquipmentDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID документа')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('certificate', 'Certificate'), ('declaration', 'Declaration'), ('estimate', 'Estimate'), ('manual', 'Manual'), ('other', 'Other')], max_length=20, verbose_name='Тип документа')),
                ('document_name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='equipment_documents/', verbose_name='Файл')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('is_for_client', models.BooleanField(default=False, verbose_name='Для клиента')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Внутренний документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proposals.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Документ оборудования',
                'verbose_name_plural': 'Документы оборудования',
                'db_table': 'equipment_document',
            },
        ),
    ]
