# Generated by Django 4.2.7 on 2026-01-09 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_equipmentline_logistics_equipmentlineitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPrices',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID расхода')),
                ('price_parameter_name', models.CharField(max_length=255, verbose_name='Название параметра расхода')),
                ('expense_type', models.CharField(choices=[('packaging', 'Packaging'), ('labor', 'Labor'), ('depreciation', 'Depreciation'), ('service', 'Service'), ('warehouse', 'Warehouse'), ('other', 'Other')], max_length=20, verbose_name='Тип расхода')),
                ('value_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('coefficient', 'Coefficient')], max_length=20, verbose_name='Тип значения')),
                ('price_parameter_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Значение расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дополнительный расход',
                'verbose_name_plural': 'Дополнительные расходы',
                'db_table': 'additional_prices',
            },
        ),
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID коммерческого предложения')),
                ('proposal_name', models.CharField(max_length=255, verbose_name='Название КП')),
                ('outcoming_number', models.CharField(max_length=100, unique=True, verbose_name='Номер КП')),
                ('currency_ticket', models.CharField(max_length=10, verbose_name='Валюта')),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Курс валюты')),
                ('exchange_rate_date', models.DateField(blank=True, null=True, verbose_name='Дата курса валюты')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Итоговая цена')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Себестоимость')),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент маржи')),
                ('proposal_date', models.DateField(verbose_name='Дата КП')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Срок действия КП')),
                ('delivery_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время доставки')),
                ('warranty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гарантия')),
                ('proposal_status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлено'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('negotiating', 'В переговорах'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('proposal_version', models.PositiveIntegerField(verbose_name='Версия КП')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('bitrix_lead_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Битрикс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='proposals.client', verbose_name='Клиент')),
                ('parent_proposal', models.ForeignKey(blank=True, db_column='parent_proposal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_proposals', to='proposals.commercialproposal', verbose_name='Родительское КП')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'db_table': 'commercial_proposal',
                'ordering': ['-proposal_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи списка')),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент налога')),
                ('tax_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма налога')),
                ('delivery_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент доставки')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('additional_price', models.ForeignKey(blank=True, db_column='additional_price_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_lists', to='proposals.additionalprices', verbose_name='Дополнительный расход')),
            ],
            options={
                'verbose_name': 'Список оборудования',
                'verbose_name_plural': 'Списки оборудования',
                'db_table': 'equipment_list',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID платежа')),
                ('payment_name', models.CharField(max_length=255, verbose_name='Название платежа')),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payment_log',
            },
        ),
        migrations.CreateModel(
            name='EquipmentListLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество линий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('equipment_line', models.ForeignKey(db_column='equipment_line_id', on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='proposals.equipmentline', verbose_name='Линия оборудования')),
                ('equipment_list', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='proposals.equipmentlist', verbose_name='Список оборудования')),
            ],
            options={
                'verbose_name': 'Элемент списка (линия)',
                'verbose_name_plural': 'Элементы списка (линии)',
                'db_table': 'equipment_list_line_item',
                'unique_together': {('equipment_list', 'equipment_line')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество единиц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='proposals.equipment', verbose_name='Единица оборудования')),
                ('equipment_list', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items_relation', to='proposals.equipmentlist', verbose_name='Список оборудования')),
            ],
            options={
                'verbose_name': 'Элемент списка (оборудование)',
                'verbose_name_plural': 'Элементы списка (оборудование)',
                'db_table': 'equipment_list_item',
                'unique_together': {('equipment_list', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='equipment_items',
            field=models.ManyToManyField(blank=True, related_name='equipment_lists', through='proposals.EquipmentListItem', to='proposals.equipment', verbose_name='Единицы оборудования'),
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='equipment_lines',
            field=models.ManyToManyField(blank=True, related_name='equipment_lists', through='proposals.EquipmentListLineItem', to='proposals.equipmentline', verbose_name='Линии оборудования'),
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='proposal',
            field=models.ForeignKey(blank=True, db_column='proposal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_lists', to='proposals.commercialproposal', verbose_name='Коммерческое предложение'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='payment_logs',
            field=models.ManyToManyField(blank=True, related_name='commercial_proposals', to='proposals.paymentlog', verbose_name='Платежи'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Создал КП'),
        ),
    ]
