# Generated by Django 4.2.7 on 2026-01-09 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_additionalprices_commercialproposal_equipmentlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID курса')),
                ('currency_from', models.CharField(choices=[('RUB', 'Российский рубль (RUB)'), ('CNY', 'Китайский юань (CNY)'), ('USD', 'Доллар США (USD)'), ('KZT', 'Казахстанский тенге (KZT)'), ('EUR', 'Евро (EUR)')], max_length=10, verbose_name='Валюта (из)')),
                ('currency_to', models.CharField(choices=[('RUB', 'Российский рубль (RUB)'), ('CNY', 'Китайский юань (CNY)'), ('USD', 'Доллар США (USD)'), ('KZT', 'Казахстанский тенге (KZT)'), ('EUR', 'Евро (EUR)')], default='KZT', max_length=10, verbose_name='Валюта (в)')),
                ('rate_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Значение курса')),
                ('rate_date', models.DateField(verbose_name='Дата курса')),
                ('source', models.CharField(choices=[('api_cbr', 'API Центрального банка России'), ('api_nbrk', 'API Национального банка РК'), ('api_other', 'Другое API'), ('manual', 'Ручной ввод'), ('custom', 'Корректировка для КП')], default='manual', max_length=20, verbose_name='Источник курса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_official', models.BooleanField(default=True, verbose_name='Официальный курс')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exchange_rates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('proposal', models.ForeignKey(blank=True, db_column='proposal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_adjustments', to='proposals.commercialproposal', verbose_name='КП (для корректировки)')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'exchange_rate',
                'ordering': ['-rate_date', '-created_at'],
                'indexes': [models.Index(fields=['currency_from', 'currency_to', 'rate_date', 'is_active'], name='exchange_ra_currenc_24b8e4_idx'), models.Index(fields=['rate_date', 'is_active'], name='exchange_ra_rate_da_fa1f56_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(condition=models.Q(('proposal__isnull', True)), fields=('currency_from', 'currency_to', 'rate_date', 'proposal'), name='unique_official_rate_per_date'),
        ),
    ]
