# Generated by Django 4.2.7 on 2026-01-13 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_exchangerate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCalculation',
            fields=[
                ('calculation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID расчёта')),
                ('calculation_version', models.PositiveIntegerField(default=1, verbose_name='Версия расчёта')),
                ('purchase_price_id', models.IntegerField(blank=True, null=True, verbose_name='ID цены закупки')),
                ('purchase_price_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена закупки')),
                ('purchase_price_currency', models.CharField(max_length=10, verbose_name='Валюта закупки')),
                ('purchase_price_source', models.CharField(blank=True, max_length=20, null=True, verbose_name='Источник закупки')),
                ('logistics_id', models.IntegerField(blank=True, null=True, verbose_name='ID логистики')),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость логистики')),
                ('logistics_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта логистики')),
                ('logistics_route', models.CharField(blank=True, max_length=20, null=True, verbose_name='Маршрут логистики')),
                ('warehouse_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость склада')),
                ('warehouse_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта склада')),
                ('production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Производственные расходы')),
                ('production_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта производства')),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Дополнительные расходы')),
                ('additional_costs_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта доп. расходов')),
                ('exchange_rate_id', models.IntegerField(blank=True, null=True, verbose_name='ID курса валюты')),
                ('exchange_rate_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Курс валюты')),
                ('exchange_rate_from', models.CharField(max_length=10, verbose_name='Валюта (из)')),
                ('exchange_rate_to', models.CharField(default='KZT', max_length=10, verbose_name='Валюта (в)')),
                ('exchange_rate_date', models.DateField(blank=True, null=True, verbose_name='Дата курса')),
                ('total_cost_base_currency', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Итоговая себестоимость (базовая валюта)')),
                ('total_cost_kzt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Итоговая себестоимость (KZT)')),
                ('calculation_details', models.JSONField(blank=True, null=True, verbose_name='Детали расчёта')),
                ('is_manual_adjustment', models.BooleanField(default=False, verbose_name='Ручная корректировка')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='cost_calculations', to='proposals.equipment', verbose_name='Оборудование')),
                ('proposal', models.ForeignKey(blank=True, db_column='proposal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_calculations', to='proposals.commercialproposal', verbose_name='Коммерческое предложение')),
            ],
            options={
                'verbose_name': 'Расчёт себестоимости',
                'verbose_name_plural': 'Расчёты себестоимости',
                'db_table': 'cost_calculation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'proposal', 'calculation_version'], name='cost_calcul_equipme_23460d_idx'), models.Index(fields=['created_at'], name='cost_calcul_created_7b8147_idx')],
            },
        ),
    ]
