# Generated by Django 4.2.7 on 2026-01-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_costcalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='delivery_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Процент доставки'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Процент налога'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='tax_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма налога'),
        ),
    ]
