# Generated by Django 4.2.7 on 2026-01-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_make_equipment_list_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='additional_prices',
            field=models.ManyToManyField(blank=True, related_name='equipment_lists', to='proposals.additionalprices', verbose_name='Дополнительные расходы'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='additional_price',
            field=models.ForeignKey(blank=True, db_column='additional_price_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_lists_old', to='proposals.additionalprices', verbose_name='Дополнительный расход (устаревшее)'),
        ),
    ]
