# Generated by Django 4.2.7 on 2026-01-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_add_additional_prices_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproposal',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_value',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Сумма платежа'),
        ),
    ]
