# Generated by Django 4.2.7 on 2026-01-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_increase_decimal_fields_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalprices',
            name='price_parameter_value',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Значение расхода'),
        ),
        migrations.AlterField(
            model_name='costcalculation',
            name='additional_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Дополнительные расходы'),
        ),
        migrations.AlterField(
            model_name='costcalculation',
            name='production_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Производственные расходы'),
        ),
        migrations.AlterField(
            model_name='costcalculation',
            name='purchase_price_value',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Цена закупки'),
        ),
        migrations.AlterField(
            model_name='costcalculation',
            name='warehouse_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Стоимость склада'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Стоимость доставки'),
        ),
    ]
