# Generated by Django 4.2.7 on 2026-01-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_increase_all_decimal_fields_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcalculation',
            name='total_cost_base_currency',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Итоговая себестоимость (базовая валюта)'),
        ),
    ]
