# Generated by Django 4.2.27 on 2026-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_increase_total_cost_kzt_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlistitem',
            name='row_expenses',
            field=models.JSONField(blank=True, default=list, verbose_name='Расходы на строку'),
        ),
    ]
