# Generated by Django 4.2.27 on 2026-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_equipmentlistitem_row_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='internal_exchange_rates',
            field=models.JSONField(blank=True, default=list, verbose_name='Внутренние курсы валют (snapshot)'),
        ),
    ]
