# Generated by Django 4.2.27 on 2026-01-17 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_commercialproposal_internal_exchange_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Последний раз обновил'),
        ),
    ]
