# Generated by Django 4.2.27 on 2026-01-17 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_commercialproposal_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID шаблона')),
                ('content_json', models.JSONField(default=list, verbose_name='Структура контента')),
                ('is_final', models.BooleanField(default=False, verbose_name='Зафиксировано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_templates', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='proposals.commercialproposal', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'Шаблон КП',
                'verbose_name_plural': 'Шаблоны КП',
                'db_table': 'proposal_template',
            },
        ),
    ]
