# Generated by Django 4.2.27 on 2026-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_paymentlog_comments_paymentlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='margin_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма маржи'),
        ),
    ]
