# Generated by Django 4.2.27 on 2026-01-18 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_commercialproposal_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposaltemplate',
            old_name='content_json',
            new_name='layout_data',
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
