# Generated by Django 4.2.27 on 2026-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_rename_content_json_proposaltemplate_layout_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('api_cbr', 'API Центрального банка России'), ('api_nbrk', 'API Национального банка РК'), ('api_other', 'Другое API'), ('manual', 'Ручной ввод'), ('custom', 'Корректировка для КП')], default='manual', max_length=20, verbose_name='Источник'),
        ),
    ]
