# Generated by Django 4.2.27 on 2026-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_alter_exchangerate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Техническое название')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок раздела')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон раздела',
                'verbose_name_plural': 'Шаблоны разделов',
                'db_table': 'section_templates',
            },
        ),
    ]
