# Generated by Django 4.2.27 on 2026-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_sectiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='additional_services',
            field=models.JSONField(blank=True, default=list, verbose_name='Дополнительные услуги'),
        ),
    ]
