# Generated by Django 4.2.27 on 2026-01-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0029_commercialproposal_additional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_imagelinks',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки на изображения'),
        ),
    ]
