# Generated by Django 4.2.27 on 2026-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0030_alter_equipment_equipment_imagelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип компании')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
                'db_table': 'system_settings',
            },
        ),
    ]
