# Generated by Django 4.2.27 on 2026-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaltemplate',
            name='header_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные заголовка'),
        ),
    ]
