# Generated by Django 4.2.27 on 2026-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0032_proposaltemplate_header_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentlistitem',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Элемент списка (оборудование)', 'verbose_name_plural': 'Элементы списка (оборудование)'},
        ),
        migrations.AddField(
            model_name='equipmentlistitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
