# Generated by Django 4.2.27 on 2026-01-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0033_add_order_to_equipment_list_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='data_package',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Пакет данных для конструктора'),
        ),
    ]
