# Generated by Django 4.2.27 on 2026-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0035_add_price_fields_to_equipment_list_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sale_price_kzt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена продажи (KZT)'),
        ),
    ]
