# Generated by Django 4.2.27 on 2026-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0036_add_sale_price_kzt_to_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlistitem',
            name='calculated_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Расчетные данные (маржа, расходы и т.д.)'),
        ),
    ]
