# Generated by Django 4.2.27 on 2026-02-01 16:16

from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0040_bitrix_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentphoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to=proposals.models.equipment_photo_upload_to, verbose_name='Фото'),
        ),
    ]
