# Generated by Django 4.2.27 on 2026-03-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0044_crmdeal_stage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='satu_api_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Токен Satu.kz'),
        ),
        migrations.AlterField(
            model_name='crmdeal',
            name='stage_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Код стадии (Bitrix)'),
        ),
    ]
