# Generated by Django 4.2.27 on 2026-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0045_systemsettings_satu_api_token_alter_crmdeal_stage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='header_kz_info',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты (KZ)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='header_ru_info',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты (RU)'),
        ),
    ]
