# Generated by Django 4.2.27 on 2026-05-16 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0046_systemsettings_header_kz_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('markup', 'Надбавка'), ('discount', 'Скидка')], max_length=10, verbose_name='Тип')),
                ('value_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение (%)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('proposal', models.ForeignKey(db_column='proposal_id', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='proposals.commercialproposal', verbose_name='Коммерческое предложение')),
            ],
            options={
                'verbose_name': 'Надбавка/Скидка КП',
                'verbose_name_plural': 'Надбавки/Скидки КП',
                'db_table': 'proposal_adjustment',
                'ordering': ['created_at'],
            },
        ),
    ]
