# Generated by Django 4.2.27 on 2026-05-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0047_proposaladjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Менеджер', 'Менеджер'), ('Младший менеджер', 'Младший менеджер'), ('Просмотр', 'Просмотр')], max_length=50, verbose_name='Роль'),
        ),
    ]
