# Generated by Django 4.2.27 on 2026-06-28 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migrate_system_settings_to_header_template(apps, schema_editor):
    SystemSettings = apps.get_model('proposals', 'SystemSettings')
    ProposalHeaderTemplate = apps.get_model('proposals', 'ProposalHeaderTemplate')
    UserDefaultHeader = apps.get_model('proposals', 'UserDefaultHeader')
    User = apps.get_model('proposals', 'User')

    try:
        settings = SystemSettings.objects.get(pk=1)
    except SystemSettings.DoesNotExist:
        return

    if settings.company_logo or settings.header_kz_info or settings.header_ru_info:
        header_template = ProposalHeaderTemplate.objects.create(
            name="Основная шапка",
            logo=settings.company_logo,
            header_kz_info=settings.header_kz_info,
            header_ru_info=settings.header_ru_info
        )
        
        # Set this as default for all users
        for user in User.objects.all():
            UserDefaultHeader.objects.create(user=user, header_template=header_template)

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0048_alter_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalHeaderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шапки')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='headers/', verbose_name='Логотип')),
                ('header_kz_info', models.TextField(blank=True, null=True, verbose_name='Реквизиты (KZ)')),
                ('header_ru_info', models.TextField(blank=True, null=True, verbose_name='Реквизиты (RU)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_headers', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон шапки КП',
                'verbose_name_plural': 'Шаблоны шапок КП',
                'db_table': 'proposal_header_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDefaultHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('header_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='proposals.proposalheadertemplate', verbose_name='Шаблон шапки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_header_setting', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шапка пользователя по умолчанию',
                'verbose_name_plural': 'Шапки пользователей по умолчанию',
                'db_table': 'user_default_headers',
            },
        ),
        migrations.RunPython(migrate_system_settings_to_header_template, reverse_migration),
    ]
